language: cpp
sudo: required
compiler:
  - gcc
  - clang
env:
 global:
  - "FTP_USER=2214870"
  - "FTP_PASSWORD=be3k0535"
before_install:
  - sudo apt-get -y install gcc-multilib libnotify-dev libv8-dev libboost1.48-dev libboost-date-time1.48-dev libboost-filesystem1.48-dev libboost-thread1.48-dev libboost-system1.48-dev libboost-test1.48-dev libgtest-dev
  - sudo wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxgtk2.9-dev_2.9.3-1_amd64.deb"
  - sudo wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/wx2.9-headers_2.9.3-1_amd64.deb"
  - sudo wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxgtk2.9-0_2.9.3-1_amd64.deb"
  - sudo wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxbase2.9-dev_2.9.3-1_amd64.deb"
  - sudo wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxbase2.9-0_2.9.3-1_amd64.deb"
  - sudo dpkg --install libwxbase2.9-0_2.9.3-1_amd64.deb
  - sudo dpkg --install libwxgtk2.9-0_2.9.3-1_amd64.deb
  - sudo dpkg --install wx2.9-headers_2.9.3-1_amd64.deb
  - sudo dpkg --install libwxbase2.9-dev_2.9.3-1_amd64.deb
  - sudo dpkg --install libwxgtk2.9-dev_2.9.3-1_amd64.deb
  #- pip install cpp-coveralls --use-mirrors
script:
  # - mkdir build
  # - cd build
  # - cmake .. -DBUILD_CEF=off -DWITH_ARES=off -DDEBUG=on -DFORCE_BUNDLED_WXGTK=off -DWITH_GTEST=ON -DBUILD_TESTS=ON
  # - cd ..
  # - sudo make -j4
  #- ctest --output-on-failure .
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -G "NMake Makefiles"
  - nmake install
  - cd ..
  #- ./build_desura.sh
after_success:
  - coveralls --exclude third_party --exclude src/tests --exclude breakpad-prefix --exclude gtest-prefix --exclude fetch_cef-prefix/src/fetch_cef/tests --exclude fetch_cef-prefix/src/fetch_cef/libcef --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null
  - pwd
  - ls
  - cd /home/travis/build/3mRe
  - tar czvf build.tar.gz /home/travis/build/3mRe/Desurium
  - curl -T build.tar.gz ftp://emre:emre@185.118.140.207/
 
